---
# Sub playbook to start all services on the relevant machines

- hosts: ip-172-31-24-55
  tasks:
    - name: Start namenode
      service: name=namenode state=started

    - name: Start resourcemanager
      service: name=resourcemanager state=started

- hosts: zookeepers
  tasks:
    - name: Start zookeeper
      service: name=zookeeper state=started

- hosts: workers
  tasks:
    - name: Start datanode
      service: name=datanode state=started

    - name: Start nodemanager
      service: name=nodemanager state=started

    - name: Start HBase regionserver
      service: name=hbase state=started

- hosts: cluster
  tasks:
    - name: Start HBase
      service: name=hbase state=started